# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Saurabh Kashyap <saurabhkashyap0001@gmail.com>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf