version: '3.7'

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio_container
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
      - MINIO_SERVER_URL=
    volumes:
      - minio-data:/data
volumes:
  minio-data:
    driver: local