version: '3.7'

# secrets:
#   # Secrets are single-line text files where the sole content is the secret
#   # Paths in this example assume that secrets are kept in local folder called ".secrets"
#   DB_ROOT_PWD:
#     file: .secrets/db_root_pwd.txt
#   MYSQL_PWD:
#     file: .secrets/mysql_pwd.txt
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'

     # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
     
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
    # config for mariaDB
      # DB_MYSQL_HOST: "db"
      # DB_MYSQL_PORT: 3306
      # DB_MYSQL_USER: "npm"
      # DB_MYSQL_PASSWORD: "npm"
      # DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      # DB_MYSQL_NAME: "npm"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
      # ADD Origin policy
      # X_FRAME_OPTIONS: "sameorigin"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    # secrets:
    #   - MYSQL_PWD
    # depends_on:
    #   - db

  # db:
  #   image: 'jc21/mariadb-aria:latest'
  #   restart: unless-stopped
  #   environment:
      # MYSQL_ROOT_PASSWORD: "npm"  # use secret instead
      # MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
      # MYSQL_DATABASE: "npm"
      # MYSQL_USER: "npm"
      # # MYSQL_PASSWORD: "npm"  # use secret instead
      # MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
      # secrets:
      # - DB_ROOT_PWD
      # - MYSQL_PWD


  # More Info https://nginxproxymanager.com/setup/#configuration-file