name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/rollout:$(date +%s) .
          echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker tag rollout:$(date +%s) ${{ secrets.DOCKER_USER }}/rollout
          docker push ${{ secrets.DOCKER_USER }}/rollout
